xebialabs/xl-up-blueprint

xl-infra/blueprint.yaml, xl-up/blueprint.yaml, xl-up/generated_answers.yaml.tmpl, xl-up/xebialabs/answers.yaml.tmpl, xl-up/xebialabs/common.yaml.tmpl, xl-up/xebialabs/xl-k8s-foundation.yaml.tmpl
=> LOVE-1162 use secretFiles

xl-up/xebialabs/kubernetes/efk-stack/elasticsearch/deployment.yaml.tmpl, xl-up/xebialabs/kubernetes/efk-stack/elasticsearch/rbac.yaml.tmpl, xl-up/xebialabs/kubernetes/efk-stack/fluentd/rbac.yaml.tmpl, xl-up/xebialabs/kubernetes/efk-stack/kibana/ingress.yaml.tmpl, xl-up/xebialabs/kubernetes/pg-stack/grafana/pvc.yaml.tmpl, xl-up/xebialabs/kubernetes/pg-stack/kube-state-metrics/kube-state-metrics-cluster-role-binding.yaml.tmpl, xl-up/xebialabs/kubernetes/pg-stack/kube-state-metrics/kube-state-metrics-cluster-role.yaml.tmpl, xl-up/xebialabs/kubernetes/pg-stack/kube-state-metrics/kube-state-metrics-role-binding.yaml.tmpl, xl-up/xebialabs/kubernetes/pg-stack/kube-state-metrics/kube-state-metrics-role.yaml.tmpl, xl-up/xebialabs/kubernetes/pg-stack/prometheus/deployment.yaml.tmpl, xl-up/xebialabs/kubernetes/pg-stack/prometheus/rbac.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-deploy/external-db/active-active/export-pvc.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-deploy/external-db/active-active/work-pvc.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-deploy/local-db/xld-deployment-single-node.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/aws-efs/aws-efs-rbac.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/aws-efs/aws-efs-storageclass.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/aws-gp2-storageclass.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/gcp-pd-retain-storageclass.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/ha-proxy-ingress-controller/ingress-controller.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/nfs-client-provisioner/deployment.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/nfs-client-provisioner/rbac.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/nfs-client-provisioner/storageclass.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/postgresql/xl-postgresql.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-release/external-db/active-active/pvc.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-release/local-db/xlr-deployment-single-node.yaml.tmpl
=> LOVE-1274: Add labels for undeployment purposes; Change names of cluster resources

integration_tests.py, xl-infra/blueprint.yaml, xl-up/blueprint.yaml
=> LOVE-1216: Use expression in some ignoreIfSkipped params

xl-infra/blueprint.yaml, xl-infra/cm_answer_file_auto.yaml.tmpl, xl-up/blueprint.yaml, xl-up/generated_answers.yaml.tmpl, xl-up/xebialabs/answers.yaml.tmpl, xl-up/xebialabs/common.yaml.tmpl, xl-up/xebialabs/xl-k8s-foundation.yaml.tmpl
=> Love-1277: Remove k8s connect params from config map

integration_tests.py
=> update xl binary

Jenkinsfile-release, LICENSE.txt
=> Add jenkins release job

xl-up/xebialabs/kubernetes/efk-stack/elasticsearch/rbac.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/aws-efs/aws-efs-storageclass.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/aws-gp2-storageclass.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/gcp-pd-retain-storageclass.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/nfs-client-provisioner/rbac.yaml.tmpl
=> LOVE-1309 correct namespaces

xl-up/xebialabs/kubernetes/xl-k8s-foundation/ha-proxy-ingress-controller/default-backend.yaml.tmpl
=> REL-9130 fix HEAD http method from lowercase to uppercase

xl-infra/blueprint.yaml, xl-up/generated_answers.yaml.tmpl, xl-up/xebialabs/answers.yaml.tmpl
=> LOVE-1312 remove unwanted entries from answer

xl-up/xebialabs/kubernetes/efk-stack/kibana/dashboard-job.yaml.tmpl
=> LOVE-1316 - Add init container to wait for kibana

xl-up/blueprint.yaml, xl-up/xebialabs/answers.yaml.tmpl, xl-up/xebialabs/xl-deploy.yaml.tmpl, xl-up/xebialabs/xl-k8s-foundation.yaml.tmpl, xl-up/xebialabs/xl-release.yaml.tmpl
=> LOVE-1298: increase timeout of k8s deployment to 10 minutes

integration-tests/test-cases/k8s-token-auth/test-gke-xlr-mon.yaml, integration-tests/test-cases/k8s-token-auth/test-on-prem-xlr-mon.yaml, integration-tests/test-cases/provisioned-db/test-eks-xlr-mon.yaml, integration-tests/test-cases/provisioned-db/test-gke-xlr-mon.yaml, integration-tests/test-cases/provisioned-db/test-on-prem-xlr-mon.yaml, xl-up/xebialabs/xl-k8s-foundation.yaml.tmpl
=> LOVE-1385: Fix rabbitmq, xld and update tests

integration-tests/test-cases/custom-docker-registry/test-local-xld-xlr.yaml, integration-tests/test-cases/custom-docker-registry/test-local-xld.yaml, integration-tests/test-cases/custom-docker-registry/test-local-xlr.yaml, integration-tests/test-cases/external-db/test-local-xld-xlr.yaml, integration-tests/test-cases/external-db/test-local-xld.yaml, integration-tests/test-cases/provisioned-db/test-local-xld-xlr.yaml, integration-tests/test-cases/provisioned-db/test-local-xld.yaml, integration-tests/test-cases/provisioned-db/test-local-xlr.yaml, xl-up/blueprint.yaml, xl-up/generated_answers.yaml.tmpl, xl-up/xebialabs/answers.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-deploy/local-db/xld-deployment-single-node.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/postgresql/xl-postgresql.yaml.tmpl, xl-up/xebialabs/xl-k8s-foundation.yaml.tmpl
=> Love 1388: Remove persistent volumes on local k8s

xl-infra/blueprint.yaml, xl-up/blueprint.yaml
=> LOVE-882 add validation for file path

xl-up/blueprint.yaml, xl-up/xebialabs/deployments.yaml.tmpl, xl-up/xebialabs/xl-k8s-foundation.yaml.tmpl
=> LOVE-1404 use an md5 hash for unique config name

xl-up/xebialabs/kubernetes/xl-deploy/external-db/active-active/xld-deployment-master.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-deploy/local-db/xld-deployment-single-node.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-k8s-foundation/postgresql/xl-postgresql.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-release/external-db/active-active/xlr-deployment-active.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-release/local-db/xlr-deployment-single-node.yaml.tmpl
=> LOVE-1406: Create the schemas in postgres form a job

Jenkinsfile-release, xl-up/blueprint.yaml
=> LOVE-1411: empty value for docker username

xl-up/blueprint.yaml
=> Love 1380 - Fix XlrDeploymentTimeout showing when it shouldn't

xl-infra/blueprint.yaml
Added prompt to remove aws credentials check from quick setup if present and ask for key if not
**General**
**Testing**
=> LOVE-1409 Fix AWS Credentials  

integration-tests/test-cases/custom-docker-registry/test-eks-xld-mon.yaml, xl-up/blueprint.yaml, xl-up/xebialabs/deployments.yaml.tmpl, xl-up/xebialabs/xl-deploy.yaml.tmpl, xl-up/xebialabs/xl-k8s-foundation.yaml.tmpl, xl-up/xebialabs/xl-release.yaml.tmpl
=> LOVE-1430 use hash for deployment names

xl-infra/blueprint.yaml
=> LOVE-1427 Fixed GKE token being to long for some editors

Jenkinsfile
=> update-seed-version Updated to 9.6.1-alpha.2

Jenkinsfile
=> LOVE-1475 Update to 9.6.0

integration-tests/test-cases/jenkins/eks-xld-xlr-mon-full.yaml, integration-tests/test-cases/jenkins/gke-xld-xlr-mon-full.yaml, integration-tests/test-cases/jenkins/on-prem-xld-xlr-mon-full-windows.yaml, integration-tests/test-cases/jenkins/on-prem-xld-xlr-mon-full.yaml
=> LOVE-1518 Fixed Jenkins test files for custom namespace

.github/pull_request_template.md, xl-up/generated_answers.yaml.tmpl, xl-up/xebialabs/answers.yaml.tmpl
=> fix hybrid cluster param on answer files

.github/pull_request_template.md, xl-up/generated_answers.yaml.tmpl, xl-up/xebialabs/answers.yaml.tmpl, xl-up/xebialabs/kubernetes/efk-stack/fluentd/daemonset.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-deploy/external-db/active-active/xld-deployment-master.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-deploy/local-db/xld-deployment-single-node.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-release/external-db/active-active/xlr-deployment-active.yaml.tmpl, xl-up/xebialabs/kubernetes/xl-release/local-db/xlr-deployment-single-node.yaml.tmpl
=> LOVE-1521 Remove privileged: true from K8s containers that don't need to be

integration-tests/test-cases/custom-namespace/test-azure-xld-xlr-mon.yaml, integration-tests/test-cases/custom-namespace/test-eks-xld-xlr-mon.yaml, integration-tests/test-cases/custom-namespace/test-gke-xld-xlr-mon.yaml, integration-tests/test-cases/custom-namespace/test-on-prem-xld-xlr-mon.yaml, integration-tests/test-cases/external-ingress/test-azure-xld-xlr-mon.yaml, integration-tests/test-cases/external-ingress/test-eks-xld-xlr-mon.yaml, integration-tests/test-cases/external-ingress/test-gke-xld-xlr-mon.yaml, integration-tests/test-cases/external-ingress/test-on-prem-xld-xlr-mon.yaml, integration-tests/test-cases/provisioned-db/test-azure-xld-xlr-mon.yaml, integration-tests/test-cases/provisioned-db/test-eks-xld-xlr-mon.yaml, integration-tests/test-cases/provisioned-db/test-gke-xld-xlr-mon.yaml, integration-tests/test-cases/provisioned-db/test-on-prem-xld-xlr-mon.yaml, xl-up/xebialabs/kubernetes/efk-stack/es-curator/cronjob.yaml.tmpl
=> LOVE-1529 Modified cronjob to point to new registry

docs/readme-AGIC-ing-controller.md, docs/readme-gloo-ing-controller.md, docs/readme-nginx-ing-controller.md
=> Test Custom Ingress Controllers

xl-up/blueprint.yaml
=> LOVE-1547 Added to answer config map hash

build.gradle.kts
=> ENG-8955 bump release version

build.gradle.kts
=> Fix job version to sync 10.2

build.gradle.kts
=> Use versionToSync to synchronize nexus to dist

build.gradle.kts, buildSrc/build.gradle.kts, gradle.properties, gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat, publish.sh, publish_local.sh, publish_snapshot.sh
=> S-92340 upgrade to gradle 8
